### ISSUE TITLE
Uniformize canonical urls

### ISSUE THREAD

**Issue by nriss** [ansforge/ROR_ressource-conformance#1]
Some have double shashes, ex: https://github.com/ansforge/ROR_ressource-conformance/blob/2.4/ROR_HealthcareService_AvailableTime_OpenClose.StructureDefinition.xml

**Comment by sdemeyANS** [comment]
another one 

`StructureDefinition xmlns="http://hl7.org/fhir">
  <url value="http://esante.gouv.fr//fhir/StructureDefinition/ROR_AvailableTime_NumberDaysofWeek" />`

https://github.com/ansforge/ROR_ressource-conformance/blob/2.4/StructureDefinition/ROR_HealthcareService_AvailableTime_NumberDaysofWeek.StructureDefinition.xml
