### ISSUE TITLE
Mise à jour nom slicing pour être iso 2.4

### ISSUE THREAD

**Issue by nriss** [ansforge/ROR_ressource-conformance#20]
[input/fsh/extensions/ROROrganizationTerritorial.fsh](https://github.com/ansforge/FIG_ans.fhir.fr.ror30/pull/6/files/95beaa166c1b571b20bfec2833e44fb40e71da09#diff-0e7a07d8b7d5651a29c438bb565f2b12a8e4607bcf6868133a34086a483cea76)

Mettre un nom fonctionnel ou concept métier au lieu des  datatypes pour les extensions lignes 12 et 13

Modification apportée par @TristanKEREVAL en 3.0

**Comment by sdemeyANS** [comment]
Archivage du repo
